// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmtpLXwrLYOe8rLDf7SrvNmp_AHUEm_i8',
    appId: '1:929015066105:web:17e3eb538af3219d69e128',
    messagingSenderId: '929015066105',
    projectId: 'chatapp-ad94d',
    authDomain: 'chatapp-ad94d.firebaseapp.com',
    databaseURL: 'https://chatapp-ad94d-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ad94d.appspot.com',
    measurementId: 'G-VXR52G1J0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCz6QXQSEkFW4zt31wk49l2H_2BSgIQo',
    appId: '1:929015066105:android:cd06c45d47600ae869e128',
    messagingSenderId: '929015066105',
    projectId: 'chatapp-ad94d',
    databaseURL: 'https://chatapp-ad94d-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ad94d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5zIJFgZLbgSMfv82YoQA53BkI8Z5o0oY',
    appId: '1:929015066105:ios:0e38b239ec09c57569e128',
    messagingSenderId: '929015066105',
    projectId: 'chatapp-ad94d',
    databaseURL: 'https://chatapp-ad94d-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ad94d.appspot.com',
    iosClientId: '929015066105-gdpaqofq8j9a626uiurv3fp41huhcjv2.apps.googleusercontent.com',
    iosBundleId: 'com.edwin.biteboxJubinProj',
  );
}
